/**
 * Generates docs/ADO_SAMPLE_PREVIEW.md — approximate text a user sees in Azure DevOps
 * for a sample Slack→bug intake (same HTML builders as production).
 *
 * Run: npm run preview:ado
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  appendSlackSourceToDescriptionHtml,
  buildAdoAcceptanceCriteriaHtml,
  buildAdoDescriptionWithSlackFallback,
  buildAdoTcmReproStepsHtml,
  buildAdoTcmSystemInfoHtml,
  buildSlackBugDeploymentMetaHtml,
  buildSlackMediaEmbedsHtml,
  normalizeSeverityForAdo,
} from "../src/lib/azure-devops";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outPath = join(root, "docs", "ADO_SAMPLE_PREVIEW.md");

function decodeEntities(s: string): string {
  return s
    .replaceAll("&amp;", "&")
    .replaceAll("&lt;", "<")
    .replaceAll("&gt;", ">")
    .replaceAll("&quot;", '"')
    .replaceAll("&#39;", "'");
}

/** Readable markdown-ish view of ADO HTML (Boards still renders real HTML). */
function adoHtmlToMarkdownApprox(html: string): string {
  let s = html;
  s = s.replace(/<hr[^>]*>/gi, "\n\n---\n\n");
  s = s.replace(/<br\s*\/?>/gi, "\n");
  s = s.replace(/<\/p>/gi, "\n\n");
  s = s.replace(/<\/div>/gi, "\n");
  s = s.replace(/<li>/gi, "\n- ");
  s = s.replace(/<\/li>/gi, "");
  s = s.replace(/<\/ol>\s*<p>/gi, "\n\n<p>");
  s = s.replace(/<\/ol>|<\/ul>/gi, "\n");
  s = s.replace(/<ol>|<ul>/gi, "\n");
  s = s.replace(/<b>([^<]*)<\/b>/gi, "**$1**");
  s = s.replace(/<span>([^<]*)<\/span>/gi, "$1");
  s = s.replace(
    /<img[^>]*src="([^"]+)"[^>]*alt="([^"]*)"[^>]*\/?>/gi,
    "\n\n![$2]($1)\n\n",
  );
  s = s.replace(/<i>([^<]*)<\/i>/gi, "*$1*");
  s = s.replace(/<a href="([^"]+)"[^>]*>([^<]*)<\/a>/gi, "[$2]($1)");
  s = s.replace(/<[^>]+>/g, "");
  return decodeEntities(s).replace(/\n{3,}/g, "\n\n").trim();
}

const sampleIntake = {
  deployment_environment: "prod" as const,
  platform: "Android",
  preconditions: ["Koppert.one opened as Admin", "Overview page is open"],
  stepsToReproduce: [
    "Open Planner tab",
    "Add three products with quantities",
    "Tap Order",
    "Confirm checkout",
  ],
  actualResult: "Two identical orders appear in the list.",
  expectedResult: "Only one order should be created.",
  notes: ["Reproduces on Samsung Galaxy A35"],
};

const slackMessageText =
  "prod, Android. On Planner I added 3 lines and tapped Order — got duplicate orders in the list.";

const title = "Duplicate order created from Planner on Android";

process.env.SLACK_BUG_APP_BUILD = process.env.SLACK_BUG_APP_BUILD || "3.5.0_OTA_2";

const descriptionBodyHtml =
  buildSlackBugDeploymentMetaHtml() +
  buildAdoDescriptionWithSlackFallback(
    {
      deployment_environment: sampleIntake.deployment_environment,
      platform: sampleIntake.platform,
      preconditions: sampleIntake.preconditions,
      stepsToReproduce: sampleIntake.stepsToReproduce,
      actualResult: sampleIntake.actualResult,
      expectedResult: sampleIntake.expectedResult,
      notes: sampleIntake.notes,
    },
    slackMessageText,
  );

const fakeAttachmentUrl =
  "https://dev.azure.com/your-org/_apis/wit/attachments/00000000-0000-0000-0000-000000000001?fileName=slack-screenshot.png";

const embedHtml = buildSlackMediaEmbedsHtml([
  {
    url: fakeAttachmentUrl,
    fileName: "slack-screenshot.png",
    contentType: "image/png",
  },
]);

const fullDescription = appendSlackSourceToDescriptionHtml(
  descriptionBodyHtml + embedHtml,
  {
    permalink:
      "https://your-workspace.slack.com/archives/C0123456789/p1234567890123456",
    channelId: "C0123456789",
    messageTs: "1234567890.123456",
  },
);

const reproStepsHtml = buildAdoTcmReproStepsHtml(
  sampleIntake.stepsToReproduce,
  sampleIntake.actualResult,
);
const systemInfoHtml = buildAdoTcmSystemInfoHtml({
  deployment_environment: sampleIntake.deployment_environment,
  platform: sampleIntake.platform,
  preconditions: sampleIntake.preconditions,
  notes: sampleIntake.notes,
});
const acceptanceHtml = buildAdoAcceptanceCriteriaHtml(
  sampleIntake.expectedResult,
);

const severity = normalizeSeverityForAdo("high");
const adoSeverityPicklist: Record<string, string> = {
  critical: "1 - Critical",
  high: "2 - High",
  medium: "3 - Medium",
  low: "4 - Low",
};
const appendTags = ["Production"];

const md = `# Sample: what Azure DevOps would show (Slack → Buggybot)

_This file is generated by \`npm run preview:ado\`. It uses the same HTML builders as production; Boards renders **HTML** on the Description tab — below is a **plain-text / Markdown-style** reading._

---

## Work item fields (summary)

| Field | Sample value |
|-------|----------------|
| **Work item type** | Bug |
| **Title** | ${title} |
| **Severity** | \`${adoSeverityPicklist[severity]}\` (\`Microsoft.VSTS.Common.Severity\`) |
| **Tags** | ${appendTags.join("; ")} _(when \`deployment_environment === "prod"\`)_ |
| **Assigned to** | _(optional; from your assignment mode)_ |

---

## Description tab (\`System.Description\`)

${adoHtmlToMarkdownApprox(fullDescription)}

---

## Repro Steps tab (\`Microsoft.VSTS.TCM.ReproSteps\` or your process ref)

${adoHtmlToMarkdownApprox(reproStepsHtml) || "_empty if your Bug type hides this field or steps were empty_"}

---

## System Info tab (\`Microsoft.VSTS.TCM.SystemInfo\` or your process ref)

${adoHtmlToMarkdownApprox(systemInfoHtml) || "_empty_"}

---

## Acceptance Criteria tab (\`Microsoft.VSTS.Common.AcceptanceCriteria\` or your process ref)

${adoHtmlToMarkdownApprox(acceptanceHtml) || "_empty_"}

---

## Attachments

After a successful Slack media step, the same image URL as in Description is also linked as an **AttachedFile** on the work item (download + preview in ADO).

---

## Raw HTML (Description only, for debugging)

\`\`\`html
${fullDescription}
\`\`\`
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, md, "utf8");
console.log(`Wrote ${outPath}`);
